sudo: false
language: node_js
node_js:
  - "6"
  - "8"
  - "10"
notifications:
  email:
    recipients:
      - "devel-mojito@yahoo-inc.com"
      - "ypt-team@yahoo-inc.com"
    on_success: change
    on_failure: always
  irc:
    channels:
      - "irc.freenode.org#mojito"
    on_success: change
    on_failure: always
